# Generated by Django 3.2.20 on 2024-12-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmatch',
            name='processed',
            field=models.BooleanField(blank=True, db_column='Processed', default=False, null=True),
        ),
    ]
