# Generated by Django 3.2.20 on 2024-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bestmatch_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_note_ref_no',
            field=models.CharField(blank=True, db_column='Delivery_Note_Ref_No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='gia',
            field=models.FloatField(blank=True, db_column='gia', default=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='item_no',
            field=models.CharField(blank=True, db_column='Item_No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='product_description',
            field=models.CharField(blank=True, db_column='Product_Description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='quantity',
            field=models.FloatField(blank=True, db_column='Quantity', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='unit_of_measure',
            field=models.CharField(blank=True, db_column='Unit_of_Measure', max_length=50, null=True),
        ),
    ]
