# Generated by Django 3.2.20 on 2024-12-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241215_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestmatch',
            name='gia',
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='account_number',
            field=models.TextField(blank=True, db_column='account_number', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='building_id',
            field=models.BigIntegerField(blank=True, db_column='Building_ID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='data_source',
            field=models.TextField(blank=True, db_column='Data_Source', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='declared_unit',
            field=models.TextField(blank=True, db_column='Declared_Unit', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_address_line_1',
            field=models.TextField(blank=True, db_column='Delivery_Address_Line_1', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_city',
            field=models.TextField(blank=True, db_column='Delivery_City', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_country',
            field=models.TextField(blank=True, db_column='Delivery_Country', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_note_ref_no',
            field=models.CharField(blank=True, db_column='Delivery_Note_Ref_No', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_post_code',
            field=models.TextField(blank=True, db_column='Delivery_Post_code', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='delivery_to',
            field=models.TextField(blank=True, db_column='Delivery_to', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='email',
            field=models.TextField(blank=True, db_column='Email', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='filename',
            field=models.TextField(blank=True, db_column='Filename', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='item_no',
            field=models.BigIntegerField(blank=True, db_column='Item_No', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='material_name',
            field=models.TextField(blank=True, db_column='Material_Name', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='phase_id',
            field=models.BigIntegerField(blank=True, db_column='Phase_ID', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='phone',
            field=models.TextField(blank=True, db_column='Phone', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='product_company_name',
            field=models.TextField(blank=True, db_column='Product_Company_Name', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='product_description',
            field=models.TextField(blank=True, db_column='Product_Description', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='product_name',
            field=models.TextField(blank=True, db_column='Product_Name', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='purchase_order_no',
            field=models.TextField(blank=True, db_column='Purchase_Order_No', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='supplier_address_line_1',
            field=models.TextField(blank=True, db_column='Supplier_Address_Line_1', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='supplier_city',
            field=models.TextField(blank=True, db_column='Supplier_City', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='supplier_country',
            field=models.TextField(blank=True, db_column='Supplier_Country', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='supplier_name',
            field=models.TextField(blank=True, db_column='Supplier_Name', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='supplier_post_code',
            field=models.TextField(blank=True, db_column='Supplier_Post_code', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='unit_of_measure',
            field=models.TextField(blank=True, db_column='Unit_of_Measure', null=True),
        ),
        migrations.AlterField(
            model_name='bestmatch',
            name='user_id',
            field=models.TextField(blank=True, db_column='User_ID', null=True),
        ),
    ]
