# Generated by Django 3.2.20 on 2024-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20241215_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmatch',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, db_column='entry_time', null=True),
        ),
    ]
