# Generated by Django 3.2.20 on 2024-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bestmatch_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmatch',
            name='entry_time',
            field=models.DateTimeField(auto_now=True, db_column='entry_time', null=True),
        ),
    ]
